
name: textureForge
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8
  - numpy=1.24.3
  - matplotlib=3.7.1
  - notebook
  - ipython
  - ipykernel
  - pip
  - pip:
    - pillow
    - opencv-python
    - wandb
    - tensorboard
    - tqdm
    - hydra-core
    - scikit-image
